/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guessword;

import static java.lang.Integer.max;
import java.util.Random;
import sun.security.util.Length;

/**
 *
 * @author w1549747
 */
public class Hangman1 extends javax.swing.JFrame {
    Random random = new Random();
    int number   = random.nextInt(6);
    String FindWord;
    String Word[]={"nintendo","corsair","single","hello","ring","toy",};  
    
    /**
     * Creates new form Hangman1
     */
    public Hangman1() {
        initComponents();
        HangmanImage.setIcon(new javax.swing.ImageIcon("F:/University Work/NetBeansProjects/Guessword/HangmanImage/0life.png"));
       
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Char0 = new javax.swing.JLabel();
        Char1 = new javax.swing.JLabel();
        Char2 = new javax.swing.JLabel();
        Char3 = new javax.swing.JLabel();
        Char4 = new javax.swing.JLabel();
        aLetter = new javax.swing.JTextField();
        Mistake = new javax.swing.JLabel();
        MyMessage = new javax.swing.JLabel();
        tryLetter = new javax.swing.JButton();
        HangmanImage = new javax.swing.JButton();
        Correct = new javax.swing.JLabel();
        Char5 = new javax.swing.JLabel();
        Char6 = new javax.swing.JLabel();
        Char7 = new javax.swing.JLabel();
        Char8 = new javax.swing.JLabel();
        Char9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Char0.setText("X");
        getContentPane().add(Char0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 20, 42));

        Char1.setText("X");
        getContentPane().add(Char1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 20, 42));

        Char2.setText("X");
        getContentPane().add(Char2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 20, 42));

        Char3.setText("X");
        getContentPane().add(Char3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 20, 42));

        Char4.setText("X");
        getContentPane().add(Char4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 20, 42));
        getContentPane().add(aLetter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 30));

        Mistake.setText("0");
        getContentPane().add(Mistake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 30));

        MyMessage.setText("look here");
        getContentPane().add(MyMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 110, 20));

        tryLetter.setText("Try Letter");
        tryLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryLetterActionPerformed(evt);
            }
        });
        getContentPane().add(tryLetter, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 110, 30));

        HangmanImage.setText("jButton1");
        HangmanImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HangmanImageActionPerformed(evt);
            }
        });
        getContentPane().add(HangmanImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 350, 250));

        Correct.setText("0");
        getContentPane().add(Correct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, 30));

        Char5.setText("X");
        getContentPane().add(Char5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 20, 42));

        Char6.setText("X");
        getContentPane().add(Char6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 20, 42));

        Char7.setText("X");
        getContentPane().add(Char7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 20, 42));

        Char8.setText("X");
        getContentPane().add(Char8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 20, 42));

        Char9.setText("X");
        getContentPane().add(Char9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 20, 42));

        jLabel1.setText("Incorrect Guesses");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel2.setText("Correct Guesses");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tryLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryLetterActionPerformed
        int CorrectGuess = Integer.parseInt(Correct.getText());
        
        FindWord = Word[number];
        int IncorrectGuess = Integer.parseInt(Mistake.getText());
        String letter = aLetter.getText();
        int charPos = FindWord.indexOf(letter); 
        int Length=FindWord.length();
        String Blank = "";
        String LoseMessage = "You Lost!";
        String WinMessage = "You Win!";
        
        
        if (Length == 1) {
            Char1.setVisible(false);Char2.setVisible(false);
            Char3.setVisible(false);Char4.setVisible(false);
            Char5.setVisible(false);Char6.setVisible(false);
            Char7.setVisible(false);Char8.setVisible(false);
            Char9.setVisible(false); }    
        if (Length == 2) {
            Char2.setVisible(false);
            Char3.setVisible(false);Char4.setVisible(false);
            Char5.setVisible(false);Char6.setVisible(false);
            Char7.setVisible(false);Char8.setVisible(false);
            Char9.setVisible(false);} 
        if (Length == 3) {
            Char3.setVisible(false);Char4.setVisible(false);
            Char5.setVisible(false);Char6.setVisible(false);
            Char7.setVisible(false);Char8.setVisible(false);
            Char9.setVisible(false);} 
        if (Length == 4) {
            Char4.setVisible(false);Char5.setVisible(false);
            Char6.setVisible(false);Char7.setVisible(false);
            Char8.setVisible(false);Char9.setVisible(false);} 
        if (Length == 5) {
            Char5.setVisible(false);Char6.setVisible(false);
            Char7.setVisible(false);Char8.setVisible(false);
            Char9.setVisible(false);} 
        if (Length == 6) {
            Char6.setVisible(false);Char7.setVisible(false);
            Char8.setVisible(false);Char9.setVisible(false);}
        if (Length == 7) {
            Char7.setVisible(false); Char8.setVisible(false);
            Char9.setVisible(false);}
        if (Length == 8) {
            Char8.setVisible(false);Char9.setVisible(false);}
        if (Length == 9) {
            Char9.setVisible(false);} 
        
        if (charPos == -1 && IncorrectGuess < 11) {
        IncorrectGuess = IncorrectGuess + 1;
        String TheWrongGuess = Integer.toString(IncorrectGuess);
        Mistake.setText(TheWrongGuess);
        aLetter.setText(Blank);     
        }
   
        if (charPos == 0) {
        Char0.setText(letter);
        charPos = FindWord.indexOf(letter,charPos+1);
        CorrectGuess = CorrectGuess + 1;
        String TheCorrectGuess = Integer.toString(CorrectGuess);
        Correct.setText(TheCorrectGuess);
        aLetter.setText(Blank);
        }
        if (charPos == 1) {
        Char1.setText(letter);
        charPos = FindWord.indexOf(letter,charPos+1);
        CorrectGuess = CorrectGuess + 1;
        String TheCorrectGuess = Integer.toString(CorrectGuess);
        Correct.setText(TheCorrectGuess);
        aLetter.setText(Blank);
        }
        if (charPos == 2) {
        Char2.setText(letter);
        charPos = FindWord.indexOf(letter,charPos+1);
        CorrectGuess = CorrectGuess + 1;
        String TheCorrectGuess = Integer.toString(CorrectGuess);
        Correct.setText(TheCorrectGuess);
        aLetter.setText(Blank);
        }        
        if (charPos == 3) {
        Char3.setText(letter);
        charPos = FindWord.indexOf(letter,charPos+1);
        CorrectGuess = CorrectGuess + 1;
        String TheCorrectGuess = Integer.toString(CorrectGuess);
        Correct.setText(TheCorrectGuess);
        aLetter.setText(Blank);
        }        
        if (charPos == 4) {
        Char4.setText(letter);
        charPos = FindWord.indexOf(letter,charPos+1);
        CorrectGuess = CorrectGuess + 1;
        String TheCorrectGuess = Integer.toString(CorrectGuess);
        Correct.setText(TheCorrectGuess);
        aLetter.setText(Blank);
        }
        if (charPos == 5) {
        Char5.setText(letter);
        charPos = FindWord.indexOf(letter,charPos+1);
        CorrectGuess = CorrectGuess + 1;
        String TheCorrectGuess = Integer.toString(CorrectGuess);
        Correct.setText(TheCorrectGuess);
        aLetter.setText(Blank);
        }
        if (charPos == 6) {
        Char6.setText(letter);
        charPos = FindWord.indexOf(letter,charPos+1);
        CorrectGuess = CorrectGuess + 1;
        String TheCorrectGuess = Integer.toString(CorrectGuess);
        Correct.setText(TheCorrectGuess);
        aLetter.setText(Blank);
        }
        if (charPos == 7) {
        Char7.setText(letter);
        charPos = FindWord.indexOf(letter,charPos+1);
        CorrectGuess = CorrectGuess + 1;
        String TheCorrectGuess = Integer.toString(CorrectGuess);
        Correct.setText(TheCorrectGuess);
        aLetter.setText(Blank);
        }
        if (charPos == 8) {
        Char8.setText(letter);
        charPos = FindWord.indexOf(letter,charPos+1);
        CorrectGuess = CorrectGuess + 1;
        String TheCorrectGuess = Integer.toString(CorrectGuess);
        Correct.setText(TheCorrectGuess);
        aLetter.setText(Blank);
        }
        if (charPos == 9) {
        Char9.setText(letter);
        charPos = FindWord.indexOf(letter,charPos+1);
        CorrectGuess = CorrectGuess + 1;
        String TheCorrectGuess = Integer.toString(CorrectGuess);
        Correct.setText(TheCorrectGuess);
        aLetter.setText(Blank);
        }
        
        if (IncorrectGuess == 1){
        HangmanImage.setIcon(new javax.swing.ImageIcon("F:/University Work/NetBeansProjects/Guessword/HangmanImage/1life.png"));  
        }
        if (IncorrectGuess == 2){
        HangmanImage.setIcon(new javax.swing.ImageIcon("F:/University Work/NetBeansProjects/Guessword/HangmanImage/2life.png"));  
        }
        if (IncorrectGuess == 3){
        HangmanImage.setIcon(new javax.swing.ImageIcon("F:/University Work/NetBeansProjects/Guessword/HangmanImage/3life.png"));  
        }
        if (IncorrectGuess == 4){
        HangmanImage.setIcon(new javax.swing.ImageIcon("F:/University Work/NetBeansProjects/Guessword/HangmanImage/4life.png"));  
        }
        if (IncorrectGuess == 5){
        HangmanImage.setIcon(new javax.swing.ImageIcon("F:/University Work/NetBeansProjects/Guessword/HangmanImage/5life.png"));  
        }
        if (IncorrectGuess == 6){
        HangmanImage.setIcon(new javax.swing.ImageIcon("F:/University Work/NetBeansProjects/Guessword/HangmanImage/6life.png"));  
        }
        if (IncorrectGuess == 7){
        HangmanImage.setIcon(new javax.swing.ImageIcon("F:/University Work/NetBeansProjects/Guessword/HangmanImage/7life.png"));  
        }
        if (IncorrectGuess == 8){
        HangmanImage.setIcon(new javax.swing.ImageIcon("F:/University Work/NetBeansProjects/Guessword/HangmanImage/8life.png"));  
        }
        if (IncorrectGuess == 9){
        HangmanImage.setIcon(new javax.swing.ImageIcon("F:/University Work/NetBeansProjects/Guessword/HangmanImage/9life.png"));  
        }
        if (IncorrectGuess == 10){
        HangmanImage.setIcon(new javax.swing.ImageIcon("F:/University Work/NetBeansProjects/Guessword/HangmanImage/10life.png"));  
        }
        if (IncorrectGuess == 11){
        HangmanImage.setIcon(new javax.swing.ImageIcon("F:/University Work/NetBeansProjects/Guessword/HangmanImage/11life.png"));
        MyMessage.setText(LoseMessage);
        }
        if (CorrectGuess==Length)
        MyMessage.setText(WinMessage);
        
        
    }//GEN-LAST:event_tryLetterActionPerformed

    private void HangmanImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HangmanImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HangmanImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hangman1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hangman1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hangman1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hangman1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hangman1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Char0;
    private javax.swing.JLabel Char1;
    private javax.swing.JLabel Char2;
    private javax.swing.JLabel Char3;
    private javax.swing.JLabel Char4;
    private javax.swing.JLabel Char5;
    private javax.swing.JLabel Char6;
    private javax.swing.JLabel Char7;
    private javax.swing.JLabel Char8;
    private javax.swing.JLabel Char9;
    private javax.swing.JLabel Correct;
    private javax.swing.JButton HangmanImage;
    private javax.swing.JLabel Mistake;
    private javax.swing.JLabel MyMessage;
    private javax.swing.JTextField aLetter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton tryLetter;
    // End of variables declaration//GEN-END:variables
}
